// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWKsFmWiByJlLci_aW0zp5e8LkaUGx36k',
    appId: '1:768978480754:web:8fd8e640c18e9444c35ceb',
    messagingSenderId: '768978480754',
    projectId: 'reelsapp-f9b63',
    authDomain: 'reelsapp-f9b63.firebaseapp.com',
    storageBucket: 'reelsapp-f9b63.appspot.com',
    measurementId: 'G-3VGHK8B46P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_L80VOkhnOIsljATV43Rfv74ij_M3cs',
    appId: '1:768978480754:android:c6966188a2f32bd4c35ceb',
    messagingSenderId: '768978480754',
    projectId: 'reelsapp-f9b63',
    storageBucket: 'reelsapp-f9b63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVeildi9_TUoHfT-P37VBAluXAsFgkx7c',
    appId: '1:768978480754:ios:6f8caed974385874c35ceb',
    messagingSenderId: '768978480754',
    projectId: 'reelsapp-f9b63',
    storageBucket: 'reelsapp-f9b63.appspot.com',
    iosBundleId: 'com.example.reelsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVeildi9_TUoHfT-P37VBAluXAsFgkx7c',
    appId: '1:768978480754:ios:6f8caed974385874c35ceb',
    messagingSenderId: '768978480754',
    projectId: 'reelsapp-f9b63',
    storageBucket: 'reelsapp-f9b63.appspot.com',
    iosBundleId: 'com.example.reelsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWKsFmWiByJlLci_aW0zp5e8LkaUGx36k',
    appId: '1:768978480754:web:22203e9fbf28283cc35ceb',
    messagingSenderId: '768978480754',
    projectId: 'reelsapp-f9b63',
    authDomain: 'reelsapp-f9b63.firebaseapp.com',
    storageBucket: 'reelsapp-f9b63.appspot.com',
    measurementId: 'G-2CM0NV7022',
  );
}
